[package]
name = "auto-analyser"
version = "0.1.0"
edition = "2024"

[dependencies]
time = "0.3.43"
tokio = {version= "1.47.1", features = ["macros", "rt-multi-thread"]}
tokio-test = "0.4.4"
yahoo_finance_api = "4.1.0"
