version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: equity_analyser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Uncomment when ready to run the app in Docker
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_URL: postgres://postgres:password@postgres:5432/equity_analyser
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:
